[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "biom3"
dynamic = ["version"]
requires-python = ">= 3.8"
readme = "README.md"
license = { file = "LICENSE.txt" }
description = "Development of BioM3."
authors = [
  {name = "Addison Howe"}
]
dependencies = [
  "pytorch-lightning==2.5.1.post0",
  "axial-positional-embedding==0.3.12",
  "linear-attention-transformer==0.19.1",
  "biopython==1.85",
  "hydra-core==1.3",
  "wandb",
]

[project.scripts]
biom3 = "Stage2_source.__main__:main"
biom3-test = "Stage2_source.__main__:run_test"
