[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "biom3"
dynamic = ["version"]
requires-python = ">= 3.8"
readme = "README.md"
description = "BioM3 development and investigation."
authors = [
  {name = "Addison Howe"},
  {name = "Tarak Nandi"},
]

[project.scripts]
biom3_run_PenCL_inference = "Stage1_source.__main__:run_PenCL_inference"
biom3_run_Facilitator_sample = "Stage2_source.__main__:run_Facilitator_sample"
